---

- name: Add configurations to sysctl.conf.
  become: true
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'
    backup: '{{ sysctl_config_backup }}'
  notify: Reload sysctl

- name: Add /etc/sysctl.d directory.
  become: true
  ansible.builtin.file:
    mode: '0755'
    owner: root
    group: root
    path: /etc/sysctl.d
    state: directory

- name: Add configurations to sysctl.d.
  become: true
  ansible.builtin.template:
    src: sysctl_d.j2
    dest: >-
      {{ sysctl_path + item.order|string + '-' + item.filename
          if (item.filename | splitext)[1] == '.conf'
          else sysctl_path + item.order|string + '-' + item.filename + '.conf' }}
    owner: root
    group: root
    mode: '0644'
    backup: '{{ sysctl_config_backup }}'
  notify: Reload sysctl
  loop: "{{ sysctl_d }}"
  when:
    - item.filename is defined
    - item.order is defined
    - item.settings | length > 0
